apiVersion: apps/v1
kind: Deployment
metadata:
  name: vgame-server-dev
  namespace: vgame-server-dev
  labels:
    app: vgame-server-dev
spec:
  selector:
    matchLabels:
      app: vgame-server-dev
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vgame-server-dev
    spec:
      containers:
      - name: vgame-server-dev
        image: vincentbuiwork/vgame-server:dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 500M
          limits:
            cpu: 2
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 83
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 83
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 83
      restartPolicy: Always
