apiVersion: apps/v1
kind: Deployment
metadata:
  name: VGame-prod
  namespace: VGame-prod
  labels:
    app: VGame-prod
spec:
  selector:
    matchLabels:
      app: VGame-prod
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: VGame-prod
    spec:
      containers:
      - name: VGame-prod
        image: vincentbuiwork/VGame:prod
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.5
            memory: 500M
          limits:
            cpu: 2
            memory: 1.5Gi
        livenessProbe:
          tcpSocket:
            port: 81
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 81
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 81
      restartPolicy: Always
