apiVersion: v1
kind: Service
metadata:
  name: VGame-prod-service
  labels:
    app: VGame-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.106
  externalIPs:
  - 10.24.24.106
  ports:
  - name: http
    port: 81 #local out port
    protocol: TCP
    targetPort: 81 # container port
  selector:
    app: VGame-prod #find all pod with app name
  sessionAffinity: None
